### PR TITLE
read apdu data from file

### PR DESCRIPTION
**Pull request by yogh333**
This is to be able to stream APDU data read from a file. Each line of the file is an APDU with the following format:
```
=> CLA INS P1 P2 [DATA] 
```
APDU is sent if `=>` prefix is present.

### CODE REVIEW

**Comment by ryankurte** [comment]
seems useful! not clear on the reason for having sent and not-send APDUs? but it's probably worth stripping leading whitespace on line 176 so you can use tab to align sent / not sent objects.

(and if this is a _standard_ encoding maybe it's worth moving the decoder to a library function / adding a test?)

**Comment by yogh333** [comment]
Hi,

 Sent/not-sent APDU might be useful for testing/debugging purpose: when sending a sequence of APDUs, one of them may generate a crash. Or we can also have use cases where we would like to customise easily the list of APDU to be sent.
About stripping leading whitespace, I am not sure to understand: you propose to use tab in place of `=>` to select APDU to be sent, don't you ?

**Comment by ryankurte** [comment]
not exactly. so that if you have multiple lines you can align them:

```
=> CLA INS P1 P2 [DATA]
   CLA INS P1 P2 [DATA]
   CLA INS P1 P2 [DATA]
=> CLA INS P1 P2 [DATA]
```

should be parsable.

(i guess there's also a question of whether it is better to use a custom text encoding here rather than adding serde support to the `GenericApdu` so folks can use JSON or TOML or similar?)

**Comment by yogh333** [comment]
Hello, 

As advised, I have added `serde` support to the `GenericApdu` and updated the client so it can read a sequence of APDUs from a JSON file.

**Review by ryankurte — APPROVED** [review]
lgtm!

**Comment by yogh333** [comment]
Hi,

 Looks like I do not have the write access on this repo, and thus can't merge the PR. Could you please perform the merge ?
Thx

**Pull request merged**
